AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.testapi.aws.LambdaJavaAPI::handleRequest
      Runtime: java8
      CodeUri: ./
      Role: arn:aws:iam::515016729357:role/s3uploadlambda-role
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
